name: ktk_messenger_mobile
description: Flutter client for KTK Messenger.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  dio: ^5.4.1
  shared_preferences: ^2.2.3
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  socket_io_client: ^2.0.3+1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
